project:
  type: website
  output-dir: docs

website:
  title: "Alec-lgtm.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - projects.qmd

format:
  html:
    theme: pulse
    css: styles.css
    toc: true



