project:
  type: website
  output-dir: docs

website:
  title: "Alec Chen"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd

format:
  html:
    theme: pulse
    css: styles.css
    toc: true



